hiringproj/hiringproj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("phoneapi.urls")),
    path("admin/", admin.site.urls),
]

hiringproj/phoneapi/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add_phone, name="add_phone"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('search/', views.search_view, name='search_view'),
    path('api/search/', views.phone_search_api, name='phone_search_api'),
    path('api/export/json/', views.json_export_view, name='json_export_view'),
    path("success/", views.success_view, name="success_add_phone"),
]

hiringproj/phoneapi/models.py
from django.db import models

# Create your models here.
availability_choices = [
    (True, "موجود"),
    (False, "ناموجود"),
]


class Phone(models.Model):
    brand = models.CharField(max_length=200, verbose_name="نام برند", blank=False, null=False)
    brand_country = models.CharField(max_length=200, verbose_name="کشور برند", blank=False, null=False)
    model = models.CharField(max_length=200, verbose_name="مدل", blank=False, null=False, unique=True)
    price = models.IntegerField(verbose_name="قیمت", default=0, null=False, blank=True)
    color = models.CharField(max_length=200, verbose_name="رنگ", null=False, blank=True, default="Black")
    screen_size = models.FloatField(verbose_name="اندازه صفحه", null=False, blank=True, default=5.0)
    is_available = models.BooleanField(verbose_name="موجودی", choices=availability_choices, default=True, null=False,
                                       blank=True)
    creator_country = models.CharField(max_length=200, verbose_name="کشور سازنده", blank=True, null=False,
                                       default="China")

    def __str__(self):
        return self.model

hiringproj/phoneapi/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Phone


def validate_price(value):
    if not isinstance(value, int) or value <= 0:
        raise ValidationError("قیمت باید عددی بزرگتر از 0 باشد.")


def validate_screen_size(value):
    if value <= 0:
        raise ValidationError("اندازه صفحه باید عددی بزرگتر از 0 باشد.")


class PhoneSearchForm(forms.Form):
    search_query = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'جستجو...'
        })
    )
    brands = forms.MultipleChoiceField(
        choices=[(brand, brand) for brand in Phone.objects.values_list('brand', flat=True).distinct()],
        required=False,
        widget=forms.CheckboxSelectMultiple,
        label="انتخاب برند"
    )

    brand_country = forms.MultipleChoiceField(
        choices=[(country, country) for country in Phone.objects.values_list('brand_country', flat=True).distinct()],
        required=False,
        widget=forms.CheckboxSelectMultiple,
        label="انتخاب کشور برند"
    )

    match_countries = forms.BooleanField(
        required=False,
        label="تطابق کشور سازنده و کشور برند"
    )

    is_available = forms.BooleanField(
        required=False,
        label="فقط موجود‌ها",
    )


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
        label='Username'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
        label='Password'
    )


class PhoneForm(forms.ModelForm):
    class Meta:
        model = Phone
        fields = ['brand', 'brand_country', 'model', 'price', 'color', 'screen_size', 'is_available', 'creator_country']
        labels = {
            'brand': 'نام برند',
            'brand_country': 'کشور برند',
            'model': 'مدل',
            'price': 'قیمت',
            'color': 'رنگ',
            'screen_size': 'اندازه صفحه',
            'is_available': 'موجودی',
            'creator_country': 'کشور سازنده',
        }

        error_messages = {
            'model': {
                'unique': "مدل باید یکتا باشد.",
            },
        }

        widgets = {
            'brand': forms.TextInput(attrs={'class': 'form-control'}),
            'brand_country': forms.TextInput(attrs={'class': 'form-control'}),
            'model': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'color': forms.TextInput(attrs={'class': 'form-control'}),
            'screen_size': forms.NumberInput(attrs={'class': 'form-control'}),
            'is_available': forms.Select(attrs={'class': 'form-control'}),
            'creator_country': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_price(self):
        price = self.cleaned_data.get('price')
        validate_price(price)
        return price

    def clean_screen_size(self):
        screen_size = self.cleaned_data.get('screen_size')
        validate_screen_size(screen_size)
        return screen_size

hiringproj/phoneapi/views.py
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from phoneapi.forms import PhoneForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from .forms import LoginForm, PhoneSearchForm
from .models import Phone
from django.db.models import Q, F
from django.contrib.auth import logout
import json


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # return to where the user was before logging in
                # get the next query in url
                next = request.GET.get('next')
                if next:
                    return redirect(next)
                return redirect('index')
            else:
                form.add_error(None, 'Invalid username or password')
    else:
        form = LoginForm()

    return render(request, 'phoneapi/login.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('login')


@login_required
def index(request):
    return render(request, "phoneapi/index.html")


@login_required
def success_view(request):
    return render(request, 'phoneapi/success.html')


@login_required
def add_phone(request):
    if request.method == "GET":
        # create a form
        form = PhoneForm()
        return render(request, "phoneapi/addphone.html", {"form": form})
    elif request.method == "POST":
        form = PhoneForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("success_add_phone"))
        return render(request, "phoneapi/addphone.html", {"form": form})


@login_required
def search_view(request):
    form = PhoneSearchForm(request.GET or None)
    phones = Phone.objects.all()
    search_query = None
    if form.is_valid():
        search_query = form.cleaned_data.get('search_query')
        brands = form.cleaned_data.get('brands')
        brand_country = form.cleaned_data.get('brand_country')
        match_countries = form.cleaned_data.get('match_countries')
        is_available = form.cleaned_data.get('is_available')

        phones = get_phones_search(search_query, brands, brand_country, match_countries, is_available)
        print(len(phones), request.GET)

    return render(request, 'phoneapi/search.html', {
        'search_query': search_query if search_query else '',
        'form': form,
        'phones': phones
    })


@login_required
def phone_search_api(request):
    query = request.GET.get('query', '')
    results = Phone.objects.filter(
        Q(brand__icontains=query) |
        Q(model__icontains=query)
    ).values('id', 'brand', 'model', 'price', 'color', 'screen_size', 'is_available', 'creator_country',
             'brand_country')

    return JsonResponse(list(results), safe=False)


def get_phones_search(query, brands, brand_country, match_countries, is_available):
    phones = Phone.objects.all()

    if query:
        phones = phones.filter(
            Q(brand__icontains=query) |
            Q(model__icontains=query)
        )

    if brands:
        phones = phones.filter(brand__in=brands)

    if brand_country:
        phones = phones.filter(brand_country__in=brand_country)

    if match_countries:
        phones = phones.filter(brand_country=F('creator_country'))

    if is_available:
        phones = phones.filter(is_available=True)

    return phones


@login_required
def json_export_view(request):
    query = request.GET.get('query')
    query = None if not query else query
    brands = request.GET.getlist('brands')
    brands = None if (not brands or len(brands) < 1 or (len(brands) == 1 and brands[0] == '')) else brands
    brand_country = request.GET.getlist('brand_country')
    brand_country = None if (not brand_country or len(brand_country) < 1 or
                             (len(brand_country) == 1 and brand_country[0] == '')) else brand_country
    match_countries = request.GET.get('match_countries') and request.GET.get('match_countries') == 'true'
    match_countries = None if not match_countries else match_countries
    is_available = request.GET.get('is_available') and request.GET.get('is_available') == 'true'
    is_available = None if not is_available else is_available

    phones = get_phones_search(query, brands, brand_country, match_countries, is_available)

    phone_data = list(phones.values('brand', 'model', 'price', 'color', 'screen_size', 'is_available', 'brand_country',
                                    'creator_country'))

    response = HttpResponse(json.dumps(phone_data, ensure_ascii=False, indent=2), content_type='application/json')
    return response

hiringproj/phoneapi/templates/phoneapi/addphone.html
<!-- index.html -->
{% extends "phoneapi/base.html" %}


{% block headcustom %}
<title>فرم اضافه کردن تلفن</title>
<style>
    .required-field::after {
        content: " *";
        color: red;
    }
</style>
{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="mt-4">فرم اضافه کردن تلفن</h2>
        <p></p>
        <form method="post">
            {% csrf_token %}
            {% load custom_filters %}
            {% for field in form %}
                <div class="form-group">
                    <label class="{% if field|is_required %}required-field{% endif %}" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary mt-3">ارسال</button>
        </form>
    </div>
{% endblock %}

hiringproj/phoneapi/templates/phoneapi/base.html
<html>
<head>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block headcustom %} {% endblock %}
</head>
<body>
    <div class="container mt-3">
        <div class="mb-4">
            <a href="{% url 'index' %}" class="btn btn-secondary">بازگشت به صفحه‌ی اصلی</a>
            <a href="{% url 'logout' %}" class="btn btn-danger">خروج</a>
        </div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

hiringproj/phoneapi/templates/phoneapi/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Main Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-3">
        <div class="mb-4">
            <h2> یکی از گزینه‌های زیر را انتخاب کنید</h2>
            <a href="/admin/" class="btn btn-secondary mb-2">ورود به صفحه ادمین</a>
            <a href="{% url 'add_phone' %}" class="btn btn-primary mb-2">اضافه کردن تلفن جدید</a>
            <a href="{% url 'search_view' %}" class="btn btn-warning mb-2">انجام درخواست روی تلفن ها</a>
            <a href="{% url 'logout' %}" class="btn btn-danger mb-2">خروج</a>
        </div>
    </div>
</body>
</html>

hiringproj/phoneapi/templates/phoneapi/login.html
<!-- templates/login.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h2 class="mt-4">Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary mt-3">Login</button>
            {% if form.errors %}
                <div class="alert alert-danger mt-3">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
        </form>
    </div>
</body>
</html>

hiringproj/phoneapi/templates/phoneapi/search.html
{% extends "phoneapi/base.html" %}

{% block headcustom %}
    <title>جستجوی تلفن</title>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <form method="get">
            <div class="row">
                <div class="col-md-8">
                    <input type="text" id="search-bar" name="search_query" class="form-control" placeholder="جستجو..."
                           value={{ search_query }}>
                </div>
                <div class="col-md-4">
                    <button type="button" class="btn btn-secondary" data-toggle="collapse" data-target="#filter-options"
                            aria-expanded="false" aria-controls="filter-options">
                        فیلتر ها
                    </button>
                    <div id="filter-options" class="mt-2 collapse">
                        <div class="form-row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>انتخاب برند</label>
                                    <div>
                                        {{ form.brands }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>انتخاب کشور برند</label>
                                    <div>
                                        {{ form.brand_country }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>تطابق کشور سازنده و کشور برند</label>
                                    <div>
                                        {{ form.match_countries }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label> موجودها؟</label>
                                    <div>
                                        {{ form.is_available }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">اعمال فیلتر</button>
                    </div>
                </div>
            </div>
        </form>

        <hr>

        <div class="row mb-2">
            <div class="col-md-12 text-left">
                <button id="json-export" class="btn btn-success">گرفتن خروجی json</button>
            </div>
        </div>
        <div id="phone-table">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>نام برند</th>
                    <th>مدل</th>
                    <th>قیمت</th>
                    <th>رنگ</th>
                    <th>اندازه صفحه</th>
                    <th>موجودی</th>
                    <th>کشور برند</th>
                    <th>کشور سازنده</th>
                </tr>
                </thead>
                <tbody>
                {% for phone in phones %}
                    <tr>
                        <td>{{ phone.brand }}</td>
                        <td>{{ phone.model }}</td>
                        <td>{{ phone.price }}</td>
                        <td>{{ phone.color }}</td>
                        <td>{{ phone.screen_size }}</td>
                        <td>{{ phone.is_available|yesno:"موجود,ناموجود" }}</td>
                        <td>{{ phone.brand_country }}</td>
                        <td>{{ phone.creator_country }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#search-bar').on('keyup', function () {
                var query = $(this).val();
                $.ajax({
                    url: "{% url 'phone_search_api' %}",
                    data: {
                        'query': query
                    },
                    dataType: 'json',
                    success: function (data) {
                        var tableBody = $('#phone-table tbody');
                        tableBody.empty();

                        $.each(data, function (index, phone) {
                            tableBody.append(
                                '<tr>' +
                                '<td>' + phone.brand + '</td>' +
                                '<td>' + phone.model + '</td>' +
                                '<td>' + phone.price + '</td>' +
                                '<td>' + phone.color + '</td>' +
                                '<td>' + phone.screen_size + '</td>' +
                                '<td>' + (phone.is_available ? 'موجود' : 'ناموجود') + '</td>' +
                                '<td>' + phone.brand_country + '</td>' +
                                '<td>' + phone.creator_country + '</td>' +
                                '</tr>'
                            );
                        });
                    }
                });
            });

            // JSON Export Button Click Handler
            $('#json-export').on('click', function () {
                var query = $('#search-bar').val();
                var brands = $('input[name="brands"]:checked').map(function () {
                    return this.value;
                }).get();
                var brand_country = $('input[name="brand_country"]:checked').map(function () {
                    return this.value;
                }).get();
                var match_countries = $('#id_match_countries').is(':checked');
                var is_available = $('#id_is_available').is(':checked');

                // Construct the URL with query parameters
                var url = "{% url 'json_export_view' %}?query=" + encodeURIComponent(query) +
                    "&brands=" + encodeURIComponent(brands.join(',')) +
                    "&brand_country=" + encodeURIComponent(brand_country.join(',')) +
                    "&match_countries=" + match_countries +
                    "&is_available=" + is_available;

                // Open the JSON content in a new tab
                window.open(url, '_blank');
            });
        });
    </script>
{% endblock %}

hiringproj/phoneapi/templates/phoneapi/success.html
{% extends "phoneapi/base.html" %}

{% block headcustom %}
    <title>Success</title>
{% endblock %}

{% block content %}
    <div class="container">
        <h2>با موفقیت ذخیره شد</h2>
        <div class="mt-4">
            <a href="{% url 'index' %}" class="btn btn-primary">بازگشت به صفحه‌ی اصلی</a>
        </div>
    </div>
{% endblock %}